### ISSUE TITLE
Connecting systems

### ISSUE THREAD

**Issue by abdoufrk** [aldebjer/pysim#7]
I can't connect two system using .connect function
I can't even execute the example of connecting two systems
I get the error wavesys has no attribute connect

**Comment by aldebjer** [comment]
The documentation seems not to be up to date here unfortunately, the function of connecting system is, since pysim 2.0 through a specific connections attribute. To connect the output `output 1` from `sys1` to `input1` in `sys2` type:

`sys1.connections.add_connection("output1",sys2,"input1") `

I will update the documentation as soon as possible.

**Comment by abdoufrk** [comment]
thank you so much.
I'm using pysim to simulate my final year project of master in electrical engineer so please update the documentation as soon as possible.
thank you again :)

**Comment by aldebjer** [comment]
The documentation at http://pys.im/doc is now updated.
